### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#104]
I was just wondering whether it'd be nice to have a logo, for example for use in our github organization and on my EMS poster. This is the first thing I could come up with:

![logo](https://user-images.githubusercontent.com/17080502/185397224-be6d947d-b3e1-47a2-9701-88c4d39742b9.png)

You can clearly see that I'm not a professional designer, but perhaps it helps to inspire ;-)

**Comment by ruudvdent** [comment]
How about: ![Logo](https://user-images.githubusercontent.com/10234007/202754790-8b520175-bf10-46f3-baf5-6d21023536be.png)

**Comment by Peter9192** [comment]
Already a big improvement!

**Comment by Peter9192** [comment]
![image](https://user-images.githubusercontent.com/17080502/203531423-4bd80761-316e-41c3-b452-5ec185ccb4d8.png)

Bit more rounded version

**Comment by ruudvdent** [comment]
I like it! @Peter9192 , @Imme1992 , @chrisweij . Shall we just change it to the above one in the documentation? Until we get something better of course...

**Comment by chrisweij** [comment]
> I like it! @Peter9192 , @Imme1992 , @chrisweij . Shall we just change it to the above one in the documentation? Until we get something better of course...

Good for me, I like the new logo!

**Comment by Peter9192** [comment]
![image](https://user-images.githubusercontent.com/17080502/205317211-0755dd2a-c0a1-46b8-9e60-baca343c6e22.png)

**Comment by Peter9192** [comment]
![image](https://user-images.githubusercontent.com/17080502/209362796-2ab6ec0e-6945-4fa6-b656-efca4315950e.png)
