### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#12]
https://github.com/github/renaming

**Comment by ruudvdent** [comment]
go ahead Peter

**Comment by Imme1992** [comment]
Done. To update local clones of the repo, follow:

``` 
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
``` 

More info: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

**Comment by Imme1992** [comment]
@Imme1992 has done this on snellius and research cloud

**Comment by ruudvdent** [comment]
@ruudvdent done locally and on research cloud
@chrisweij all done
