### ISSUE TITLE
Improvement of download script

### ISSUE THREAD

**Issue by chrisweij** [WAM2layers/WAM2layers#125]
Download script is created and will be merged with pull request  #120. 
However, there are still some improvements possible: 
- Create separate (or just one) functions per level type to download data? 
- It would be ideal to download data per month (or maybe even per year if possible) to limit requests to ECMWF (and therefore possible waiting time) and then split the data afterwards. 

It might be useful to look into this script (or the era5cli package)
https://gitlab.physics.ox.ac.uk/strommen/download-era5/-/blob/master/getERA5.py
to see if we can borrow some code

**Comment by Peter9192** [comment]
We looked a bit more into the monthly/hourly challenge. It seems that this is not easily possible with the CDS API. It is possible with MARS, but that's no use. Also in the oxford code linked they write:

> #It seems like everything that isn't monthly frequency requires
> #one to download hourly data and then process. This streamlines
> #things but also will surely slow down the download: should check
> #if it's possible to relax this!

The other concerns have been addressed in #129
