### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#13]
It can be nice to use a code formatter. Consistent formatting helps to make the code readable, helps to avoid discussions about formatting, and can make for clearer diffs. A popular formatter for Python code is [black](https://black.readthedocs.io/en/stable/).

**Comment by Imme1992** [comment]
Do this when code is nearly finished, then apply code formatter again

**Comment by Imme1992** [comment]
Add instructions to developer documentation

**Comment by ruudvdent** [comment]
closed as it is indeed already part of issue #144
