### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#132]
Just did some new profiling of the code, like so:

```
# Profile the code (I cut it off at 1 day)
python -m cProfile -o profile.pstats src/wam2layers/tracking/backtrack.py cases/era5_2021_local.yaml

# Visualize the result
pip install snakeviz
snakeviz profile.pstats
```

This gives a really nice interactive graph of how much time is spent in which functions:

![image](https://user-images.githubusercontent.com/17080502/194600369-5e0e7c51-ca46-478c-8313-a776ade6da97.png)

More later

**Comment by ruudvdent** [comment]
@Peter9192 , what's the status of this issue?

**Comment by Peter9192** [comment]
I think we can close it
