### ISSUE TITLE
Check preprocessing script on boundary between two layers

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#140]
See code below, there is a comment on a ridiculous dummy pressure value. Should this be corrected or is this correct?    

```
# Insert surface level values (at a high dummy pressure value)
    u = insert_level(u, us, 110000)
    v = insert_level(v, vs, 110000)
    q = insert_level(q, qs, 110000)
    p = insert_level(p, ps, 110000)

    # Sort arrays by pressure (ascending)
    u.values = sortby_ndarray(u.values, p.values, axis=1)
    v.values = sortby_ndarray(v.values, p.values, axis=1)
    q.values = sortby_ndarray(q.values, p.values, axis=1)
    p.values = sortby_ndarray(p.values, p.values, axis=1)

    # Insert boundary level values (at a ridiculous dummy pressure value)
    p_boundary = 0.72878581 * np.array(ps) + 7438.803223
    u = insert_level(u, interpolate(p_boundary, p, u), 150000)
    v = insert_level(v, interpolate(p_boundary, p, v), 150000)
    q = insert_level(q, interpolate(p_boundary, p, q), 150000)
    p = insert_level(p, p_boundary, 150000)
```

**Comment by Peter9192** [comment]
Link to the actual code: https://github.com/WAM2layers/WAM2layers/blob/e56a7890230aad059cf4a8f938cd4705a90fae6c/src/wam2layers/preprocessing/era5.py#L114

This is not a problem, sorry if the inline comment scared you. We are inserting an additional level here, and I want to be sure that we're not accidentally overwriting data at an existing level. The actual value of the level coordinate is meaningless at this point. Later on, we are sorting by the actual value of pressure and "resetting" the level coordinate, as it "has become meaningless": 

https://github.com/WAM2layers/WAM2layers/blob/e56a7890230aad059cf4a8f938cd4705a90fae6c/src/wam2layers/preprocessing/era5.py#L121-L132

Feel free to open a PR with a better formulated inline comment 😄

**Comment by Imme1992** [comment]
Do we need to do further testing on the boundary position between the vertical layers? 
Same issue rased in issue #66

**Comment by ruudvdent** [comment]
somewhat of a duplicate with #166, so I closed this one
