### ISSUE TITLE
Copy configuration (yaml file) to output folder

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#142]

**Comment by ruudvdent** [comment]
Old issue, but perhaps we can pick this up in the next sprint. This would be really helpful to track what one did when having multiple runs.
@Peter9192 , was there some difficulty that we didn't pick this up before?

**Comment by Peter9192** [comment]
No not that I recall. I think I might have confused it with #249

**Comment by Peter9192** [comment]
closed in #249
