### ISSUE TITLE
Check the vertical fluxes

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#143]
Is it possible to use the vertical flux from the model to determine the vertical moisture flux?
Test how that affects the results
Test for winter (synoptic situation case) vs summer case (convection)

**Comment by chrisweij** [comment]
Not sure if this is the right place or if it should be a seperate issue, but I was a bit confused by the split_vertical_flux function, see below

```
def split_vertical_flux(Kvf, fv):
    f_downward = np.zeros_like(fv)
    f_upward = np.zeros_like(fv)
    f_downward[fv >= 0] = fv[fv >= 0]
    f_upward[fv <= 0] = fv[fv <= 0]
    f_upward = np.abs(f_upward)

    # include the vertical dispersion
    if Kvf != 0:
        f_upward = (1.0 + Kvf) * f_upward
        f_upward[fv >= 0] = fv[fv >= 0] * Kvf
        f_downward = (1.0 + Kvf) * f_downward
        f_downward[fv <= 0] = np.abs(fv[fv <= 0]) * Kvf

    return f_downward, f_upward
```

In the function is the fv is the vertical flux as calculated earlier. In the first line of the if statement, the upward flux is multiplied with (1 + Kvf), while in the second line it seems to be that at the same positions in the array it is multiplied with Kvf. 

So my question is, am I missing something and is done on purpose, and if not which line is the correct one?

**Comment by ruudvdent** [comment]
If `fv` is negative this means upward moisture flux. Let's assume in this example that we're talking about those locations.

Suppose there is a net flux upward, then we assume that in reality there has been more exchange:
`f_upward = (1.0 + Kvf) * f_upward`

The following line doesn't do anything for that location as `fv`is still negative:
`f_upward[fv >= 0] = fv[fv >= 0] * Kvf`

For the locations where `fv` is negative, thus upward flux, the downward flux is multiplied by just Kvf (second line)
'f_downward = (1.0 + Kvf) * f_downward
f_downward[fv <= 0] = np.abs(fv[fv <= 0]) * Kvf`

Such that the net flux is still intact. For downward moisture fluxes the opposite holds.

In principle I think we can close this issue unless we want to code it differently
