### ISSUE TITLE
Contributor documentation

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#144]
Instructions for code contributors/maintainers

**Comment by Imme1992** [comment]
Refs #13

**Comment by Imme1992** [comment]
We learned from Peter how to deal with code formatting, I make a summary here:

>pip install -e .[develop]
# with this line the packages are installed to work on development on wam2layers
# the packages that are installed for development and useful to use are black and isort and flake8

>isort src/wam2layers/tracking/backtrack.py
# isort sorts the reference to packages in a proper way
>black src/wam2layers/tracking/backtrack.py
# black formats the code based on good coding principles that can be found here: https://black.readthedocs.io/en/stable/the_black_code_style/index.html
# for example the length of code lines is reduced
>flake8 src/wam2layers/tracking/backtrack.py
# flake8 shows which lines can be improved in your script (which is what the black package actually does)

**Comment by Peter9192** [comment]
add software management plan

**Comment by ruudvdent** [comment]
**After each pull request:**

- update CHANGELOG.md under 'unreleased'

**Preparations for a release:**

- Create new branch: prep_release_vXXX

- Update "version" in pyproject.toml and in citation.cff

- describe new changes in CHANGELOG.md

**Comment by ruudvdent** [comment]
Then create the release on Github: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by Peter9192** [comment]
* sphinx: https://www.sphinx-doc.org/en/master/
* [myst-parser](https://myst-parser.readthedocs.io/en/v0.15.0/using/intro.html) or Myst-NB
* autodoc: https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#configuration
* napoleon: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#module-sphinx.ext.napoleon
* readthedocs: https://docs.readthedocs.io/en/stable/index.html
* sphinx readthedocs theme: https://pypi.org/project/sphinx-rtd-theme/

* pydantic: https://docs.pydantic.dev/
* click: https://click.palletsprojects.com/en/8.1.x/
