### ISSUE TITLE
Documentation for users

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#145]

**Comment by Imme1992** [comment]
Users should move their configuration.yaml out of the source code so they can keep their own version

**Comment by ruudvdent** [comment]
Could we not simply remove the WAM2layers/cases , because the documentation also refers to a .yaml outside of this repository

**Comment by ruudvdent** [comment]
Decided by @ruudvdent and @Peter9192 that configuration will be automatically documented in a config class that will be implemented by @Peter9192 , then the yml-s can be removed

**Comment by ruudvdent** [comment]
First stab at update in #153

**Comment by ruudvdent** [comment]
closed by #165
