### ISSUE TITLE
Create bash script to download data and run preprocessing parallel

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#148]

**Comment by ruudvdent** [comment]
Nice, could be provided as example in documentation

**Comment by Peter9192** [comment]
@Imme1992 can you add copy the script we made last wednesday in this issue? Then it's easy to add it to the docs in one of the currently active PRs

**Comment by Imme1992** [comment]
`
#!/bin/bash
#Set job requirements
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --partition=thin
#SBATCH --time=01:00:00

. /home/benedicti/miniconda3/bin/activate wam2layers

wam2layers backtrack /home/benedicti/cases_wam2layers/era5_2021_global_testperiodicboundaries_1min.yaml
`

**Comment by Peter9192** [comment]
We might want to change the `cpus-per-task` setting as this is currently probably not used effectively (most cpus idle). The `partition` setting is quite specific for snellius, so we could consider removing it or adding a comment.

**Comment by ruudvdent** [comment]
@Peter9192 @Imme1992 , is this issue still relevant?

**Comment by Peter9192** [comment]
Personally I would say it's a bit beyond scope of what we should document, but if it helps a lot of users we could include it in the documentation, I suppose. I don't think it makes sense to include it as a script in the repo.

**Comment by ruudvdent** [comment]
Beyond scope, thus closed, could be re-initiated later if relevant for a user
