### ISSUE TITLE
Separate config from actual model code

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#15]
Now, there's some hardcoded lines in all scripts with the paths to the data, e.g. 

https://github.com/WAM2layers/WAM2layers/blob/b0b90e8a795f79bbd211f54eccb765b9d626241e/Fluxes_and_States_mat.py#L86-L90

It might be more convenient to put this in a separate "experiment configuration file". That makes it possible to story many experiment configurations and run all of them without having to modify the model source code.

**Comment by Imme1992** [comment]
Yes I think that is a good idea, same accounts for latitude, longitude (depening on domain), and for the time stepping (selection of the time period to calculate the fluxes/do the tracking for)
