### ISSUE TITLE
Software management plan

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#162]
A [software management plan](https://doi.org/10.5281/zenodo.7038280) helps to implement best practices during software development and ensures that software is accessible and reusable in the short and longer term. It also contributes to the reproducibility of results and stimulates collaborative work on open-source software for research. 

We started drafting a document during the project workshop last Wednesday. It would be nice to further develop this and perhaps add it to the documentation.

**Comment by Imme1992** [comment]
https://docs.google.com/document/d/1Kvz8qMYQ3iXnHssFE1igk12nvfdXZaDjT1EZHhN6LOg/edit?usp=sharing

**Comment by ruudvdent** [comment]
convert to Word and add to Github. refer to it in developer documentation

**Comment by ruudvdent** [comment]
@Imme1992 and @Peter9192 . I have created an update (specific for the OSF project), but if you agree we can replace it as this version uses the latest 2023 template for SMPs from the eScience Center
https://docs.google.com/document/d/1gYXY_8tzNJGi6NCtvHsbbLvYha6DaaW_aDP-5NhZswU/edit?usp=sharing
