### ISSUE TITLE
Internal timestepping influences total tagged precipitation

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#171]
10min internal timestepping, tagged precip on 13-07-2021, mean outputted:
array(3415.83876358)

8min internal timestepping, tagged precip on 13-07-2021, mean outputted:
array(3417.67375862)

6min internal timestepping, tagged precip on 13-07-2021, mean outputt
array(3419.65430844)

Differences are minimal, but this actually should be exactly the same number right? 

Same holds for other timesteps for which precip is tracked.

**Comment by Imme1992** [comment]
![image](https://user-images.githubusercontent.com/18259095/207552063-b862acd2-a15d-494b-b00a-2f01e078f2d1.png)

This is a print out of the max for internal timestep 10min, 8min and 6min.

**Comment by Peter9192** [comment]
```
51533508.296875 - 51594228.453125
>> -60720.15625  # absolute

(51533508.296875 - 51594228.453125) / 51594228.453125
>> -0.001176878850028084  # relative
```

Divided by 24 (hours per day) * 2 (days) * 8 (timesteps per hour) gives a relative diff of 

```
-158.12540690104166  # absolute
-3.0647886719481356e-6  # relative
```

A single precision number has a precision of about 7-8 figures, and since we're doing a lot of calculations on them I think this could probably explain the difference.

**Comment by ruudvdent** [comment]
would be good to test an accumulation with the ERA5 input data at 1 hour timestep

**Comment by Imme1992** [comment]
There is already an issue on internal time stepping where I refer to this issue #141, therefore this issue will be closed
