### ISSUE TITLE
Trying out chatGPT: grid cell area function

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#179]
I tried asking chatGPT whether it approves of the area calculation. It had some pretty nice ideas. Overall, I was very impressed, but I noticed that the longer the conversation took, the more mistakes it made. In the end, I think this could really speed up development, even if it's just because it's faster than googling for a suitable formula as a starting point. But you need to stay sharp. I let it check itself with unit tests :-)

![image](https://user-images.githubusercontent.com/17080502/209850235-2cb2ea63-0d9a-430f-a2f1-fce3c4787fbd.png)

part 2
![image](https://user-images.githubusercontent.com/17080502/209850443-5bf59211-3ec0-459c-ba78-3f57fee67e08.png)

part 3
![image](https://user-images.githubusercontent.com/17080502/209850573-8b0a8a7f-22dc-404b-ae2a-949efaab6a14.png)

...
part n
![image](https://user-images.githubusercontent.com/17080502/209850894-6f1fb226-50e8-43db-9ba8-edb5c7eecbe3.png)

**Comment by ruudvdent** [comment]
Nice to see. Do we need to do anything with this?
- close issue?
- convert to Show and Tell in the Discussions?

**Comment by Peter9192** [comment]
Let's close it.
