### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#18]
A license enables re-use of the code. As discussed, we'd like to use Apache2, but we need to check whether there are any dependencies with a conflicting GPL licencse. 

I noticed the original version of @ruudvdent code is also GPL. The copyright holder can always re-release the code under a different license. If there are multiple co-authors, you may need to ask their permission. Some related discussion: https://opensource.stackexchange.com/q/33

Also see https://www.gnu.org/licenses/gpl-faq.en.html#Consider

**Comment by ruudvdent** [comment]
I had no idea about implications when I wrote that down. I consider myself the copyright holder, so I just changed it to Apache which should be fine then.

**Comment by Peter9192** [comment]
We also need to check whether there are no GPL-like licenses in our dependencies.

In #25 I added a minimal environment file which is enough to produce an environment that can run the code. Though it's not an exhaustive list of all packages we use, it implies that all of the other packages we use have been installed as dependencies of these few packages. If we assume that they did their homework properly, then we only need to check the license of these few packages:

* python: [python software foundation licence](https://www.python.org/download/releases/3.4.0/license/) ✔️ 
* numpy: [BSD](https://github.com/numpy/numpy/blob/main/LICENSE.txt) ✔️ 
* scipy: [BSD](https://github.com/scipy/scipy/blob/main/LICENSE.txt) ✔️ 
* netcdf4: [MIT](https://github.com/Unidata/netcdf4-python/blob/master/LICENSE) ✔️ 
* matplotlib: [PSF based](https://matplotlib.org/stable/users/project/license.html) ✔️ (note: only unused import atm)

So that looks like all green flags for apache
