### ISSUE TITLE
Update example_config

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#181]
Update example config with dates such that the time is also indicated for start and enddates

**Comment by githubyueh** [comment]
Hi there,

I tried to use the model with the example data (https://rebrand.ly/wam2layers-example-data) on the document. The backtrack step worked well, but the output files lost the first time and the last time. And when I moved to the visualize (output data) step, it did not work. The output file values at every time are all zero.

**Comment by Peter9192** [comment]
Hi Yueh,

thanks for reporting. Please beware that the model is still under active development. That means the codebase is still a bit unstable and the example data might not be completely in sync with the latest version of the code. We're hoping to arrive at a more stable version soon. Once that's released there should be a more stable version.

**Comment by ruudvdent** [comment]
Basically the same issue as #189, isn't it?

**Comment by ruudvdent** [comment]
It seems, by the way, that some new users do not find it intuitive what config setting get's used in preprocessing and what setting in tracking. That might be an argument for making that more clear in the example config
