### ISSUE TITLE
Initial experiments

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#19]
I used EC-Earth sample data that Imme sent me. I was able to start the first script `Fluxes_and_States_mat.py` (it's still running).

Initial timing and other outputs (running on my laptop) for the first 2 days:

```
2002-01-01 2002 1 1 0 31
0 = 1647616797.01
Data is loaded 16:19:57.159003
after p_maxmin and now add surface and atmosphere together for u,q,v 16:19:57.810352
before interpolation loop 16:19:57.861456
after interpolation loop 16:27:41.606369
check calculation water vapor, this value should be zero: -6.006306563222097e-14
1,2,3 = 1647617263.13
4 = 1647617263.25
5 = 1647617265.58
6a = 1647617266.78
6b = 1647617270.79
Fluxes_and_States_mat.py:527: RuntimeWarning: invalid value encountered in less
  Fa_N_top_pos[Fa_N_top_boundary < 0] = 0
Fluxes_and_States_mat.py:528: RuntimeWarning: invalid value encountered in less
  Fa_N_down_pos[Fa_N_down_boundary < 0] = 0
7 = 1647618165.04
Runtime fluxes_and_storages for day 1 in year 2002 is 1456.19814301  seconds.
2002-01-02 2002 1 2 4 31
0 = 1647618253.22
Data is loaded 16:44:13.701025
after p_maxmin and now add surface and atmosphere together for u,q,v 16:44:14.895728
before interpolation loop 16:44:14.982775
after interpolation loop 16:52:02.172743
check calculation water vapor, this value should be zero: -3.0535018957777993e-12
1,2,3 = 1647618723.58
4 = 1647618723.69
5 = 1647618724.86
6a = 1647618725.98
6b = 1647618735.02
7 = 1647618944.79
Runtime fluxes_and_storages for day 2 in year 2002 is 767.939966917  seconds.
```

So the first day took 25 minutes, second day 13 minutes. Interpolation took up 8/25 minutes for the first day and 6/13 minutes for the second day. 

Third day similar to second.

**Comment by Peter9192** [comment]
`python -m Backtrack_savedaily_mat.py` for 4 days took 285 seconds on my laptop, i.e. just under 5 minutes. So far it seems the biggest speedup can be obtained in the preprocessing.

**Comment by Peter9192** [comment]
The branch that I used for these initial tests is called `original-benchmark-version`. The associated PR (#23) contains some minor modifications I had to make in order to run the code. It also contains an environment file.

**Comment by Peter9192** [comment]
Planning to do some more benchmarking later on (and on Snellius).

**Comment by ruudvdent** [comment]
We'll look back to these numbers later
