### ISSUE TITLE
issues vs. discussion policy and rights

### ISSUE THREAD

**Issue by ruudvdent** [WAM2layers/WAM2layers#198]
I see people opening 'Issues', which often aren't really relevant for model development, but rather relate to personal errors people get when running the code that could equally well be discussed/answered under 'Discussions'. Can we implement some policy that only developers post new Issues?

**Comment by Peter9192** [comment]
We could create a very simple [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) that points people to the discussion forum and guides them a bit in how to describe their problem or idea

**Comment by ruudvdent** [comment]
In progress. The discussion forum was updated and templates are created per #211 and #212 . @vincentdefeiter will make a start with the flow diagram to be added to the readme and documentation
