### ISSUE TITLE
Align preprocessing and tracking time loops

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#22]
Tracking depends on the output of preprocessing. Preprocessing always moves forward in time, but in the case of backtracking, it might be more convenient to do it also backward in time. That would make it possible to do pre-processing "on the fly", in parallel (with some delay), or at least with less intermediate storage requirements.

**Comment by ruudvdent** [comment]
I would prefer to keep the pre-processing and processing itself completely separated, so I don't see the need for this option.

**Comment by Imme1992** [comment]
We decided not to align this
