### ISSUE TITLE
Applying WAMlayers to cmip6 daily data

### ISSUE THREAD

**Issue by WenyuZhou-4** [WAM2layers/WAM2layers#223]
Hi,
I am trying to apply this model to the daily data from the cmip6 ecearth3 model. After changing some code, the preprocessing works fine, but when I run backtracking, the final e_track results are twice as large as normal and I don't know where the problem is coming from.
I checked the input rainfall data and the e_track from the run. The total e_track in the era5 data is about 90% of the total rainfall, but in the cmip6 data it is almost 200%, which is not normal.
The Results like:
The total precipitation of era5 from 2005-2014 of whole basin in m3 is: 2.33999433e+13
The moisture evaporation of era5 from 2005-2014 in m3 is: 2.0874286e+13, which is about 89% tracked evaporation.

The total precipitation of ecearth3 from 2005-2014 in m3 is: 2.56253844e+13
The moisture evaporation of ecearth3 from 2005-2014 in m3 is: 4.697806e+13

To solve the above problem, I have made the following attempts:
1. change the targrt_frequency in config file, once it was input_freq to 1d, target_freq to 1h, now target_freq becomes 30 minutes and 10 minutes.
change the target frequency to 0.5h: 4.6247004e+13
change the target frequency to 0.1h: 4.6078267e+13
The above is the data for 10 years, in m3, which seems to have changed a bit, but not much.
2. run era5 preprocessed data with backtrackecearth3.
Result: Runs fine. This is normal, because I only modified ds.sel(time=t.to_pydatetime() + timedelta(hours=12), drop=True) on the original backtrack code, in order to apply to cmip6 daily T12:00:00 data

This result looks like forgetting to divide by 2 somewhere, but I'm not sure. Theoretically, even if the preprocessed data is completely wrong, the final result should not be greater than the total precipitation.

I have attached my modified code and provided the data for a reference. Here is the codes and datasets: 
https://drive.google.com/drive/folders/1Klg3ADH1SZ8qyqWc8YSPp7lIE-Zi2_rq?usp=sharing

**Comment by Peter9192** [comment]
Hi @WenyuZhou-4, welcome and thanks for reporting your experiments! Nice to hear that you've made modifications to work with a different dataset. Our philosophy was that by seperating dataset-specific "pre-processing" from the actual tracking, you would not have to change the backtrack code, and we could build up a collection of pre-processing scripts over time. Would you consider opening a pull request for your ecearth pre-processing script? See the [instructions here](https://wam2layers.readthedocs.io/en/latest/develop.html).

With respect to your issue: can you make a comparison between the pre-processed files from era5 and ec-earth (so the pre-processed data _before_ running the actual tracking model)? What are the differences in total precipitation, total evaporation, total moisture in upper and lower layers?

**Comment by WenyuZhou-4** [comment]
@Peter9192 Sure, because I'm a beginer of github, I'll trying to learn how to open a pull request later. 
For precipitation and evaporation, I calculated 10 years accumulation, here are the results in $m^3$. For the era5 flux and storage data I only sum` time = T12:00:00` because the ECEarth3 data is in daily in T12:00. So I think nothing wrong in the preprocessed data.

**Era5 2005-2014 in $m^3$**
The total precip is: 2.33999433e+13
The total evap is: 1.33598121e+13
The total S-lower flux is: 7.5783324e+15
The total S-upper flux is: 6.0184287e+15
The total x-lower flux is: -1.2593061e+11
The total x-upper flux is: 9.455313e+10
The total y-lower flux is: 9.820788e+10
The total y-upper flux is: 3.3203857e+10

**Ecearth3 2005-2014 in $m^3$**
The total precip is: 2.56253844e+13
The total evap is: 1.58620117e+13
The total S-lower flux is: 7.5447344e+15
The total S-upper flux is: 5.907282e+15
The total x-lower flux is: -1.4754603e+11
The total x-upper flux is: 9.872298e+10
The total y-lower flux is: 6.239756e+10
The total y-upper flux is:3.1812233e+10

**Comment by WenyuZhou-4** [comment]
I found one difference between CMIP6 data and ERA5 data is that the latitude in CMIPdata is flipped, which in ERA5 backtracking the latitude is decreasing so the `convergence `return positive fy_gradient, but in CMIP data latitude is incerasing. I'll trying to change the fy result of `convergence ` function to negative and find the result.

**Comment by Peter9192** [comment]
Right, that is important indeed! I remember I wrote some function to check whether the input is correct (there might be more things we can check, but this is a good start). However, I see they are commented out currently:

https://github.com/WAM2layers/WAM2layers/blob/3f052342474ad70c86b06696fbb290a57f20aea8/src/wam2layers/preprocessing/era5.py#L313-L315

For your fix, please correct the latitude direction in the preprocessing script and leave the tracking code untouched.

**Comment by ruudvdent** [comment]
First step will be to check the pressure level code for ERA-5, perhaps this problem is related. #115
