### ISSUE TITLE
Pydantic version issue

### ISSUE THREAD

**Issue by pkeys** [WAM2layers/WAM2layers#228]
Hi,
This is to flag a potential issue with Pydantic versions, and the work-around that I implemented.
-pat

I have just installed Wam2layers on a new computer (Macbook Pro, 2023), and during the initial run of the wam2layers, I received the following error: 
![image](https://github.com/WAM2layers/WAM2layers/assets/30704657/bd9362b4-9a1f-45d2-bc23-e00c008ee65e)

The error suggested that @root_validator in Pydantic was deprecated, so I went to the Pydantic docs here: https://docs.pydantic.dev/dev-v2/usage/errors/#root-validator-pre-skip
Then, I looked into the Migration Guide: https://docs.pydantic.dev/dev-v2/migration/

Based on the suggestion on this page, I tried installing an earlier version of Pydantic (pip install "pydantic==1.*"). This, uninstalled pydantic 2.0.2, and installed pydantic version 1.10.11.

After this, the wam2layers code ran without error.

**Comment by Peter9192** [comment]
Thanks for reporting! Indeed, pydantic has just released a new major version, so we should update it on our side. Will look into that next week.
