### ISSUE TITLE
Visualization function complains about reading in file of last timestep (00.10)

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#247]
When calling the visualization function >wam2layers visualize output it gives an error as the last (or first) timestep is saved as 00.10, while the other files are all having the name of 00.00

**Comment by Peter9192** [comment]
It is expected that the final timestep is not at midnight, but we might want to educate the visualizion script about that. Let me explain.

To do backtracking, you need to know the moisture transport between two timesteps. We do this by looking at the difference between one time point in ERA5 and the next (or previous, depending on what direction you look in). If we download era5 data from, say, 1 January, the first time there is 00:00. That means the first difference calculation can be made only for the first time step *after* 00:00, i.e. 00:10 for a 10-minute timestamp.
