### ISSUE TITLE
Better testing

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#261]
Currently we run a test to verify that the code is still able to run the example use case. This is good, but we can do better. It would be nice to:

1. Verify that the output is still the same (within acceptable margin). 
2. Also test pre-processing for a sample of ERA5 data
3. Generate idealized flow fields for which the moisture transport is predictable. Probably make this 2d (one layer only) and only test the (horizontal) transport terms. This needs some refactoring of the core tracking code. We could use a streamfunction to generate a flow field, release a patch of moisture, then do forward tracking followed by backtracking to see how much of the original moisture is returned to the source.

**Comment by geek-yang** [comment]
The first two bullet points are addressed by PR #265.

**Comment by Peter9192** [comment]
I've opened https://github.com/WAM2layers/WAM2layers/issues/357 for the last point, so we can close this.
