### ISSUE TITLE
Visualisation bug

### ISSUE THREAD

**Issue by chrisweij** [WAM2layers/WAM2layers#268]
When plotting input data with the command 'wam2layers visualize input config_file.yaml

'KeyError: 'Cannot get left slice bound for non-unique label: datetime.datetime(2021, 7, 13, 0, 0)'
Here, the datetime is derived from the config file (start date of the event). It used to work just fine a few months ago.

**Comment by chrisweij** [comment]
Seemed to be a pandas problem, but updating pandas did not work.

**Comment by Peter9192** [comment]
Look's like there's duplicate times in your input data ("non-unique label")

**Comment by ruudvdent** [comment]
likely a local problem, also visualization is being updated, thus close
