### ISSUE TITLE
Backtracking output file format issue

### ISSUE THREAD

**Issue by chrisweij** [WAM2layers/WAM2layers#269]
When backtracking the last backtracking file (so first in 'real' time) is saved in a different format, e.g.:

-rw-rw---- 1 cweijenborg prjs0202 18512018 Oct  4 15:42 backtrack_2022-02-01T04:00.nc
-rw-rw---- 1 cweijenborg prjs0202 18512018 Oct  4 15:42 backtrack_2022-02-01T03:00.nc
-rw-rw---- 1 cweijenborg prjs0202 18512018 Oct  4 15:42 backtrack_2022-02-01T02:00.nc
-rw-rw---- 1 cweijenborg prjs0202 18512018 Oct  4 15:42 backtrack_2022-02-01T01:10.nc

Then file of the  time step is saved with a timestamp 10 minutes of what should be expected (backtrack_2022-02-01T01:00.nc)

**Comment by Peter9192** [comment]
This is because the calculation of 00:00 needs input data for 23:50, which is not available for the first day. WAM2layers writes output both every hour (or whatever else you set the output freq to), and the last fields before it finishes.

**Comment by chrisweij** [comment]
Thanks, I also realised that myself, that is why I closed it.

**Comment by Peter9192** [comment]
Thanks for tidying up! 

If someone else runs into the same problem and finds this issue, it's nice if there's some helpful closing message. That's why I added another comment 😉
