### ISSUE TITLE
Use xarray

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#28]
Currently we use numpy arrays as the main data type in the model, the netCDF4 library for reading and writing netCDF, and scipy for reading and writing intermediate matlab files. 

[xarray](https://docs.xarray.dev/en/latest/index.html) is a very nice library for working with netCDF data. Compared to the 'bare' netCDF4 library, it is "higher" level, more tailored towards common operations in climate data processing. Under the hood, it also uses numpy arrays (or dask, more on that later), but it adds a nice layer with labels on top of it, just like pandas does for 2d arrays. 

For example, the following bit of code:

```python
from netCDF4 import Dataset

q = Dataset(datapath[0], mode = 'r').variables['Q'][begin_time:(begin_time+count_time+1),:,latnrs,lonnrs] #kg/kg
time = Dataset(datapath[0], mode = 'r').variables['time'][begin_time:(begin_time+count_time+1)]
q_levels = Dataset(datapath[0], mode = 'r').variables['lev'][:]
```

using xarray, would look like:

```Py
import xarray as xr
ds = xr.open_dataset(datapath[0]).sel(time=slice(begin_time, end_time)).isel(lat=latnrs, lon=lonnrs)
q = ds.Q
time = ds.time
q_levels = ds.levels
```

notice that you can use "sel" to select based on the label (e.g. `sel(time='2002-01-01')`) and "isel" to select based on the index (`isel(time=0)`). Label-based indexing makes working with the data much easier and helps to avoid bugs related to error-prone positional indexing.

xarray also provides a nice visual representation of what is in a dataset:

```py
print(ds)

<xarray.Dataset>
Dimensions:  (lon: 444, lat: 267, lev: 5, time: 124)
Coordinates:
  * lon      (lon) float64 210.2 210.4 210.6 210.8 ... 309.2 309.4 309.6 309.8
  * lat      (lat) float64 69.82 69.59 69.37 69.14 ... 10.68 10.46 10.23 10.01
  * lev      (lev) float64 8.5e+04 7e+04 5e+04 3e+04 2e+04
  * time     (time) datetime64[ns] 2002-01-01T06:00:00 ... 2002-02-01
Data variables:
    Q        (time, lev, lat, lon) float32 ...
Attributes:
    CDI:          Climate Data Interface version 1.6.9 (http://mpimet.mpg.de/...
    Conventions:  CF-1.0
    history:      Wed Jul 26 15:08:11 2017: cdo sellonlatbox,-150,-50,10,70 Q...
    institution:  European Centre for Medium-Range Weather Forecasts
    CDO:          Climate Data Operators version 1.6.9 (http://mpimet.mpg.de/...
```

## Advantages

* Easy to work with
* Easy to parallelize later on with dask
* Possibility to use different I/O engines
* Built-in functions for interpolation, plotting, etc.
* Widely used in geosciences

I suggest to gradually introduce xarray, starting with the reading and writing of netCDF file and later on perhaps also replacing some of the bare numpy arrays (in order to finally be able to leverage dask).

**Comment by Imme1992** [comment]
We changed to the xarray package to read in and write out data
