### ISSUE TITLE
units and details in onscreen logging output

### ISSUE THREAD

**Issue by ruudvdent** [WAM2layers/WAM2layers#280]
We might get:

Stability correction applied to 16.5% of grid. Average correction was 45532.9, maximum correction was 1689801.5562748688. The total correction field is written to /home/rjvanderent/Moisture_tracking_cases/floodcase_202107_new_fv/output_data/debug/stability_correction_20210715-000000.nc.
2021-07-15 00:00:00 - Tracked moisture: 0.01%. Lost moisture: -0.01%. Time since start: 0.79s, RAM: 20.82 MB
2021-07-15 00:00:00 - Writing output to file /home/rjvanderent/Moisture_tracking_cases/floodcase_202107_new_fv/output_data/backtrack_2021-07-15T00-00.nc

Add info:

- unit of the correction
- when new stability correction info will be given
- tracked moisture in %, provide info on percentage of what
- lost moisture in %, provide info on percentage of what 
- lost moisture field (can it be found somewhere, or what logging setting should be set in the yaml to store it?)

**Comment by Peter9192** [comment]
The logging is now still a bit ad-hoc. It would be nice if the logger had access to the full state of the model. That would make it much easier to change things like this. We could consider a more object-oriented approached. Also touches on #260

**Comment by ruudvdent** [comment]
Regarding losses this is solved by #305 , but not yet for the stability correction
