### ISSUE TITLE
More descriptive output files

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#287]
It would be great if we could clearly communicate the meaning of the output variables, including their units ("accumulation since previous time step" etc), by using the units and attrs fields in the netcdf file.

**Comment by Peter9192** [comment]
You're absolutely right, that's been on my mental backlog but it's good to have it here as well.

**Comment by BSchilperoort** [comment]
@ruudvdent could you give me the following info? That would allow me to add this to the output data attributes.

variable | long_name | units | description
-----------|-----------------|--------|---------------
e_track |  |  | 
s_track_upper_restart |  |  | 
s_track_lower_restart |  |  | 
p_track_upper |  |  | 
p_track_lower |  |  | 
tagged_evap |  |  | 
tagged_precip  |  |  |
losses |  |  | 
gains |  |  | 

I assume the same variables have the same meaning between backtracking and forwardtracking, or am I wrong here?

**Comment by ruudvdent** [comment]
<html><body>
<p dir="auto"><a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/ruudvdent/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/ruudvdent">@ruudvdent</a> could you give me the following info? That would allow me to add this to the output data attributes.</p>

variable | long_name | units | description
-- | -- | -- | --
e_track |   |   |  
s_track_upper_restart |   |   |  
s_track_lower_restart |   |   |  
p_track_upper |   |   |  
p_track_lower |   |   |  
tagged_evap |   |   |  
tagged_precip |   |   |  
losses |   |   |  
gains |   |   |  


</body>
</html>

**Comment by BSchilperoort** [comment]
@ruudvdent thanks! I've added them to a separate file. The units will be easy to change.
