### ISSUE TITLE
Prefer squash merge?

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#321]
[Squash merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits) is nice to keep the git history clean(er). Commits in a PR are often numerous and a bit messy (e.g. "fix typo", "apply code formatter"), whereas PRs are nice, complete chunks of work which pass tests and have a good description.

It would be nice to always do squash merges by default. If we agree on this, we could add a note to the documentation.

**Comment by BSchilperoort** [comment]
You made squash merge the only allowed option, so this issue can be closed :)
