### ISSUE TITLE
Preprocessing vs tracking

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#323]
Currently we are doing some things in the tracking module that would fit better with the preprocessing. For example, changing the units. Most importantly, I think it makes sense for all fluxes, including precip and evap, to be fed into the tracking code as "rates", i.e. units m3/s, instead of accumulations. Then,

* The tracking code will be independent of the frequency of the input data
* The time step used in tracking can be incorporated in the numerical integration step

Since this affects the backward compatibility of preprocessed data created with older versions of WAM2layers, ideally this should be decided upon and implemented before the V3 release.

**Comment by ruudvdent** [comment]
After discussion with @Peter9192 and @BSchilperoort 

- preprocessing is already in rates and standard units like [kg m-2 s-1] for E and P, and [kg m-1 s-1] for F 
- next step would be to investigate if we can drop to conversion to m3 in the tracking completely. Tracking in mass is still preferred from a point of view of following with happens, e.g., loss calculations, which would be cumbersome when tracking concentrations. Major consequence would be that the accumulated output E_track and P_track would also be in other units: [kg m-2}.
