### ISSUE TITLE
Drop support for Python 3.8

### ISSUE THREAD

**Issue by BSchilperoort** [WAM2layers/WAM2layers#326]
xarray and numpy stopped support for Python 3.8 a year ago. Later this year it will no longer receive security updates either, so it's time to drop support in wam2layers as well

_Originally posted by @BSchilperoort in https://github.com/WAM2layers/WAM2layers/pull/325#discussion_r1490700769_

**Comment by Peter9192** [comment]
Shall we make that official policy and document it somewhere?

**Comment by BSchilperoort** [comment]
The Numpy policy is explained here: https://numpy.org/neps/nep-0029-deprecation_policy.html

Support for 3.9 will also be dropped soon:

> On Apr 14, 2023 drop support for Python 3.8 (initially released on Oct 14, 2019)
On Apr 05, 2024 drop support for Python 3.9 (initially released on Oct 05, 2020)
On Apr 04, 2025 drop support for Python 3.10 (initially released on Oct 04, 2021)
On Apr 24, 2026 drop support for Python 3.11 (initially released on Oct 24, 2022)
