### ISSUE TITLE
Logged "losses" now comprises of "boundary losses" and "unaccounted water"

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#340]
I just ran the example floodcase again, and noticed the new logging behaviour from #305. I was surprised and worried to see `Lost moisture: 52.00%.`

Upon inspection of the code, I realized that the "lost moisture" now contains both "boundary losses" and "unaccounted water". I think this is slightly confusing: boundary losses are expected and nothing to worry about, even if it's a really high value. Whereas large amounts of unaccounted water is definitely a reason for concern.

Should we split them again?

**Comment by ruudvdent** [comment]
I suppose we don't have to split it in the output variable, but perhaps only in the message to the screen?

**Comment by Peter9192** [comment]
That could work. Let me try
