### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#341]
To quickly get started with WAM2layers, we made some sample data available at https://rebrand.ly/wam2layers-example-data.

Currently:

* This link points to my google drive
* The data is already pre-processed as the raw ERA5 data is too large and I wasn't sure we could redistribute it
* The sample data is for the 2021 floodcase, i.e. a backtrack run.
* The sample data does not contain good metadata.
* The existence of this sample data is documented, but it is not in plain sight. 
* I used to [use gdown](https://github.com/WAM2layers/WAM2layers/blob/359a7bd3d95a57fe1190dfc89e6cd102bf3b2c0f/.github/workflows/ci.yaml#L35) to download the data, so you could quickly obtain the reference data and run it (getting started in 1 minute)

It would be nice to extend the sample data, make it more visible, and easier to obtain.

- [x] Properly format the example data (ideally adjust preprocessing code to add better metadata, but manual adjustment is also ok as a first step)
- [x] Add a forward track case
- [x] Upload the data to a better place (zenodo, 4tu) with a DOI
- [x] Adjust the link target of rebrand.ly so users that still have that link get redirected to the new source
- [x] Add a `wam2layers download-sample-data` command to the cli? #368 
- [x] Better document the example data #367 
- [x] ~Nice to have: include raw ERA5 data? Could be a subdomain and subset of levels~ We decided to make this the default and make preprocessed data and other output the bonus.

**Comment by ruudvdent** [comment]
Forward tracking ERA5 data under review:

https://data.4tu.nl/private_datasets/JdOEDHiTlNrnrU34bTS699NSA3vUHVhU9iDdzevjm5U

**Comment by Imme1992** [comment]
Add the example cases to documentation as stated in issue #365

**Comment by Imme1992** [comment]
Forward tracking ERA5 data under review (Floodcase West Europe July 2021)
https://data.4tu.nl/private_datasets/21w70N3rU2txJbm-l6bHA4hEi6I1ox2DFFoazYJCnR8

**Comment by Peter9192** [comment]
> Forward tracking ERA5 data under review (Floodcase West Europe July 2021)

backtrack right?

**Comment by Imme1992** [comment]
Yes indeed Peter, thanks for noting, I changed it to backtrack!

**Comment by Peter9192** [comment]
I created #367 and #368 to document the example cases and make it easy to download them. 

I changed my mind about adding the config file: I think it makes more sense with the input data on 4TU (the title is already specific to WAM2layers). Also because you will need to add a corresponding source region as well.

**Comment by Peter9192** [comment]
I see both datasets are now published on 4TU 🎉 

As I feared, since the data are available via OpenDAP now (which is great!), 4TU deemed it necessary to remove the "download as zip" button, which I was using before. I've send them an email asking if they provide an API, so I could get a link to the zipfile or a file listing (either to the HTTP or OpenDAP addresses) based on the DOI.

@ruudvdent @Imme1992 have you already found some time to check and upload the config and tagging_region files?

**Comment by Peter9192** [comment]
Looking closely at the links, I see:

If the <4TU-ID> is `f9572240-f179-4338-9e1b-82c5598529e2` and <version> is `1`

* The DOI is: `10.4121/<4TU-ID>.v<version>`
* The opendap catalog is: `https://opendap.4tu.nl/thredds/catalog/data2/djht/<4TU-ID>/<version>/catalog.html`
* The files are (for opendap): `https://opendap.4tu.nl/thredds/dodsC/data2/djht/<4TU-ID>/<version>/<filename>`
* The files are (for http): `https://opendap.4tu.nl//thredds/fileServer/data2/djht/<4TU-ID>/<version>/<filename>`

So if we can get extract the file listing from the catalog, we could automatically download all files. 

Cool feature: in the future, we could use the same mechanism to directly load data via opendap. That would allow us to select a spatial subset before downloading.

**Comment by Peter9192** [comment]
We can get the catalog as xml instead of rendered HTML by changing the file extension to `.xml`. That should allow programmatic access. 

This could be of interest: https://github.com/openearth/opendap-python/tree/master

**Comment by Peter9192** [comment]
I was able to get a list of filenames using `siphon`:

```py
!pip install siphon
from siphon.catalog import TDSCatalog
cat = TDSCatalog('https://opendap.4tu.nl/thredds/catalog/data2/djht/bbe10a2a-39dc-4098-a69f-0f677d06ecdd/1/catalog.xml')
cat
cat.datasets
```

**Comment by Peter9192** [comment]
`threddsclient` gives me a list of download urls, even better!

```py
!pip install threddsclient
import threddsclient
urls = threddsclient.download_urls('https://opendap.4tu.nl/thredds/catalog/data2/djht/bbe10a2a-39dc-4098-a69f-0f677d06ecdd/1/catalog.xml')
urls
```

**Comment by Peter9192** [comment]
4TU replied very quickly! They provide an API similar to [figshare](https://docs.figshare.com/). Specifically, we can use `https://data.4tu.nl/v2/articles/<the-UUID-of-the-dataset>`.

This contains a "custom_fields -> "Data Link" attribute with the ".html" version of the catalog. Changing the extension to xml gives us the catalog.

**Comment by ruudvdent** [comment]
@Peter9192 , fix link and then close this issue

**Comment by Peter9192** [comment]
https://github.com/WAM2layers/WAM2layers/issues/390
