### ISSUE TITLE
xarray==2024.3.0 breaks tests

### ISSUE THREAD

**Issue by BSchilperoort** [WAM2layers/WAM2layers#350]
With the newest xarray version, results from the calculations (pre-processing, backtracking) are slightly different. The difference is ~0.002% but that's enough to make the tests fail.

It also is a larger error than what I'd expect with, for example, floating point errors.

Due to the nature of the data there are a lot of 0 or near-0 values in the data we try to test for regression. This makes it difficult to easily test if the changes in the data are significant or not, as relative errors (per data point) can easily get large.

For example, on the pre-processing:
```
E           Max absolute difference: 5.820766e-10
E           Max relative difference: 0.40405387
```
The largest absolute difference is quite minor, but the max relative difference is 40%.

I guess that per variable we can define what deviation is acceptable, in appropriate units (e.g. a kg/m2/s value that is translated from a value in mm/day).

**Comment by ruudvdent** [comment]
check if relevant
