### ISSUE TITLE
Add debug option to cli

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#353]
I would like to be able to print debug statements. Currently the log-level is hardcoded in to INFO for both the terminal and the log file. 

We used to have a config option for this, but it was annoying that you had to parse the config file before setting up logging at the root of the CLI. 

Ideally, I'd like to be able to add something like `--debug` or `-v`, `-vv` to get more verbose output.

**Comment by BSchilperoort** [comment]
An example of a verbosity flag is here: https://click.palletsprojects.com/en/8.1.x/options/#counting

**Comment by BSchilperoort** [comment]
Although I don't think a verbosity flag is useful in this case. The different debug levels are:

1. logging.DEBUG
2. logging.INFO
3. logging.WARNING
4. logging.ERROR
5. logging.CRITICAL

Currently `INFO` is the default for printing to the terminal. So it can only be bumped up one level to `DEBUG`.
