### ISSUE TITLE
Features: forward, time, distance, regional

### ISSUE THREAD

**Issue by ruudvdent** [WAM2layers/WAM2layers#36]
In my original code in Matlab I also had an option to calculate regional recycling within a grid cell for all grid cells at the same time (assuming water leaving the boundary of a grid cell not to return). I would possibly like to add this code as well, but it was never translated from Matlab to Python and perhaps this is not a priority.

**Comment by Peter9192** [comment]
Do you still have the MatLab code somewhere?

**Comment by ruudvdent** [comment]
Yes, and it's in principle very similar to a forward/backward tracking script (actually much simpler)

**Comment by ruudvdent** [comment]
will be done when backtracking script is considered 'finished'

**Comment by Imme1992** [comment]
Includes: #8 #35 #9

**Comment by ruudvdent** [comment]
Closed by #289 , remaining features adressed in #306
