### ISSUE TITLE
Zenodo sync failed

### ISSUE THREAD

**Issue by BSchilperoort** [WAM2layers/WAM2layers#366]
With the 3.0.0 release, the push of the release to Zenodo did not happen. 

I visited the Zenodo website, and saw that some projects were missing from the GitHub integration. On the interface it displayed that the last sync was 5 months ago, and when trying it sync it gave a 504 error.
Today I tried it again, and Zenodo sycned with GitHub. However, WAM2layers (and many many other projects...) had their integration turned off.

I turned the integration for WAM2layers on again, however that does not work retroactively so the 3.0.0 release is missing on Zenodo :disappointed:

**Comment by ruudvdent** [comment]
Can we simply do a 3.0.1 release so that the updated code is on Zenodo at least?

**Comment by Peter9192** [comment]
We could do that after #341 is addressed

**Comment by Peter9192** [comment]
Before making the new release, I checked the webhook settings on this GH repo, and noticed there were two active webhooks for zenodo integration. Having two webhooks is not good. This is the reason why zenodo restricted the management of the webhook to a single user (see https://github.com/zenodo/zenodo/issues/826). 

Since I couldn't figure out which one was which, I deleted both, hoping to setup a new clean integration. However, I cannot manage the integration on the zenodo end, I'm guessing because Bart recently flipped the switch, and apparently only one member can manage it (same issue, https://github.com/zenodo/zenodo/issues/826).

To solve this, there are two options:

* Bart should resync the zenodo integration (but he is on holiday now)
* Zenodo should reset things so I can regain the admin status and manage the integration.

I've sent an email to zenodo asking them to reset the integration.

**Comment by ruudvdent** [comment]
Would be good to have this resetted indeed (2nd option). Once fixed, let's also write down in the developer's guide who is the manager of the Zenodo integration, so we don't forget this.

**Comment by BSchilperoort** [comment]
Zenodo's GitHub settings are giving me an error 400 again. I cannot change the settings.

I feel like Zenodo's github integration is too unstable, it has been giving us issues here and on other repositories for a (long) while now.

An alternative route could be a GitHub Action workflow that pushes the new release to Zenodo. For example: https://github.com/marketplace/actions/zenodo-upload

**Comment by Peter9192** [comment]
Interesting idea. If I understand correctly, this will automatically bump the version in `citation.cff`, but not in the `__init__.py`. And it requires a bit more configuration on the repo. That could be OK, as long as we document it.

I was looking whether other people also reported/discussed similar issues with zenodo integration, to back up our gut feeling. Have you seen any?

**Comment by BSchilperoort** [comment]
> If I understand correctly, this will automatically bump the version in citation.cff

That's optional. We can use use solely for the upload.

I know that Barbara encountered it a few months ago (many repo's having their sync randomly disabled), and that Stefan also had the error 400 issue on the github integration page.

**Comment by Peter9192** [comment]
Got a reply from Zenodo today, stating that the repo was not currently enabled on zenodo. I managed to flip the switch again. First time it failed with a 400 status error, second time it worked. 

Zenodo also offered they could still the v3 release retrospectively, so I asked them to do that.

**Comment by Peter9192** [comment]
Curiously, when the Zenodo personnel tried to import the v3 release, the integration had mysteriously been disabled again. To be continued...

**Comment by Peter9192** [comment]
https://zenodo.org/records/11093876

V3 is now on zenodo

**Comment by ruudvdent** [comment]
Hoorah! But do we have a more permanent solution now?

**Comment by Peter9192** [comment]
No. We should always check whether the switch is still active before releasing. A more permanent solution could be along the lines of what Bart proposed. What I don't like about this is that it requires a Zenodo access token, which is tied to (and gives access to) a personal account, but should be stored in the settings of the repo. Perhaps we can create a dedicated zenodo account to publish wam2layers?

**Comment by ruudvdent** [comment]
Update sentence "Check that the new release is successfully rendered on Zenodo and PyPI." to first check whether Zenodo integration is turned ON on Zenodo
