### ISSUE TITLE
No moisture source output when putting periodic boundaries on True

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#378]
I have been simulating the moisture sources for an extreme precipitation case over Australia, where I want to use the global domain.
However, when I set in my config the periodic boundaries on True I do not get any output in e_track, neither in s_track_upper_restart and s_track_lower_restart.
When I set the periodic boundaries to false in the config, I do get logic e_track values etc. 

So there seems to go something wrong when periodic boundaries are applied? I have global data on a grid from -180 to 180.

**Comment by chrisweij** [comment]
I experience a similar bug for another case, everything seems to end up as 'lost moisture' immediately. I have run the same case a few days ago with the same settings, including period boundaries set to true, with an older version of WAM2layers (end of last year) without any problems. So it must have been a recent update causing these issues.

**Comment by Peter9192** [comment]
Thanks for reporting this. I suspect it may be related to the recent changes in logging/tracking "lost moisture". I can try to find some time to look into it today or tomorrow. It would hp of you could share the preprocessed data and config/region files on Snellius, so I can quickly reproduce this

**Comment by Imme1992** [comment]
Yes, I have copied the yaml file and mask to our project space in Snellius. the preprocessed data is also there.

Folder:
/projects/0/prjs0202/Australiacase/

Config file:  Australiacase_config_new.yaml
Mask: Mask_Australia_WAM2layers_new.nc
Preprocessed data in preprocessed folder

**Comment by Peter9192** [comment]
I had a few minutes today to try and I can indeed reproduce the issue. Didnt see anything suspicious in the lost moisture though, so now I suspect the padding in the advection function. Will look into it more tomorrow

**Comment by Peter9192** [comment]
I think I found the issue. There was an erroneous line in `get_boundary`:

https://github.com/WAM2layers/WAM2layers/blob/d06a8f169e8c54fdb56b5610317e144b0bfe0a06/src/wam2layers/utils/grid.py#L59-L68

The `0` on line 64 should be `:`

Submitted a fix in #379
