### ISSUE TITLE
Bugs in original code?

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#38]
In #34 I encountered a couple of things that I think might not have been intended:

The indexing for `lnsp` differs from e.g. `q2m`:

* q2m: `begin_time * 2 + 1 : (begin_time * 2 + count_time * 2 + 1) + 1 : 2`
* lnsp: `begin_time * 2 : (begin_time * 2 + count_time * 2 + 1) : 2`

There seems to be a typo in inserting the 'next' v10 value:

https://github.com/WAM2layers/WAM2layers/blob/657508c82f106b0e0681e084117a07974c864127/Fluxes_and_States_mat.py#L279-L288

**Comment by ruudvdent** [comment]
not relevant anymore
