### ISSUE TITLE
Add instructions for windows users.

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#383]
Why do you recommend this for novice users? There is no reason why the package wouldn't work on native windows, even cartopy has Windows (and ARM Mac) wheels now.

_Originally posted by @BSchilperoort in https://github.com/WAM2layers/WAM2layers/pull/367#discussion_r1632642249_

**Comment by BSchilperoort** [comment]
Full instructions for Windows install below

<hr>

- Install Python from python.org (and do check "add python to PATH" in the installer).
- Open Powershell (cmd is also possible, look [here](https://docs.python.org/3/library/venv.html) for more info).
  - Create a python virtual environment with the command `python -m venv wam2layers`
  - Activate this environment with `wam2layers\Scripts\Activate.ps1`
  - Run `pip install wam2layers`
  - Use wam2layers in the terminal like normal

Note that whenever you open a new powershell/cmd window, you will need to activate the virtual environment again.
