### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#393]
As usual, I think it would be good to create a new release that includes all the changes we made during this sprint. I think the major improvements in preprocessing justify a minor release, i.e. 3.1. I would like to reference this version in the paper, in pointing to the configurability of the A and B parameters for the interface between the pressure levels.

@BSchilperoort, would you be able to create this release today?

**Comment by BSchilperoort** [comment]
Sure I can make a new release

**Comment by Peter9192** [comment]
I agree that would be nice. On the other hand, updates to docs don't need a release to show up on RTD, right?

**Comment by BSchilperoort** [comment]
oh yeah it points to latest, not stable
