### ISSUE TITLE
Using online hosted ERA5 data as input for WAM2layers

### ISSUE THREAD

**Issue by chrisweij** [WAM2layers/WAM2layers#399]
Currently there is an online hosted version of ERA5 available (both on Pressure as well on Model levels):

https://github.com/google-research/arco-era5?tab=readme-ov-file#how-to-reproduce
https://x.com/shoyer/status/1805732055394959819

It might be nice, and would I think be quite easy, to implement a reader that directly, which also saves the user to download the data.

**Comment by chrisweij** [comment]
It is available, it might not have been available before. 
![image](https://github.com/WAM2layers/WAM2layers/assets/97346631/91a3a184-f888-4506-8964-144252e7f321)

It might be that it is calculated from vorticity/divergence, this should be checked, so then there could be small numerical differences.

**Comment by BSchilperoort** [comment]
Looks good, and would also be relatively easy to implement due to the changes in #391

**Comment by BSchilperoort** [comment]
ARCO-ERA5 data is now supported (in development branch, release to follow this friday, 20 December)
