### ISSUE TITLE
Make initial release

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#4]
Make a tagged/released version of the code so we have a reference point for future comparison. I suggest we start with version v0.1.0. Following the [semantic versioning](https://semver.org/) guidelines, v0.* implies that the version is not stable and may change frequently. 

In the process of making a release, we can as well make it citable. Here's a guide: https://guide.esciencecenter.nl/#/citable_software/making_software_citable

**Comment by Peter9192** [comment]
Just noticed @ruudvdent already versioned his code before, the latest version is v2.4.08. So starting from 0 may be confusing. I suppose in that case it makes sense to work towards a v3. But then what to do with the current version? Mark it as 2.5.0?

**Comment by ruudvdent** [comment]
Could we then perhaps mark the current version as beta-v3 or something like that?

**Comment by Peter9192** [comment]
> Could we then perhaps mark the current version as beta-v3 or something like that?

Good idea!

**Comment by Peter9192** [comment]
So it'll be "v3.0.0-beta". This is allowed by semver: "A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version".

**Comment by Peter9192** [comment]
Cool! I was able to make a "pre-release". So now there's a tag identifying v3.0.0-beta. We can add citation information etc. before making the next "official" release.
