### ISSUE TITLE
update the description of p_track_upper and p_track_lower variables in the metadata

### ISSUE THREAD

**Issue by everson-ufsm** [WAM2layers/WAM2layers#404]
Hello.
    I would like to understand what the surface precipitation is when tracking in forward mode ("tracking_direction: forward" in yaml file). In the output files (forwardtrack_*.nc files) there are: p_track_upper and p_track_lower. What is the surface precipitation? Should I add the two values together (p_track_upper + p_track_lower)? Or is the surface rainfall just the p_track_lower value?
    Sincerely,
    Everson

**Comment by Peter9192** [comment]
Dear @everson-ufsm , welcome and congrats on completing your first forward tracking experiments! `p_upper` and `p_lower` are the respective contributions from the upper and lower layers to the surface precipitation. So you can simply add them to get total precipitation at the surface.

Thanks for reaching out. Perhaps we could update the description of these variables in the metadata. Let us know if you have any more questions or feedback. 

Cheers,
Peter
