### ISSUE TITLE
WAM2layers fails to account for decreasing area of grid cells towards the poles

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#419]
@ruudvdent noticed that in the profiling code, we calculate totals without compensating for the area weights:

https://github.com/WAM2layers/WAM2layers/blob/ffee8b844af92a991a9cbe7d5f70a408f25498e6/src/wam2layers/utils/profiling.py#L70

Accounting for the weights, as per 12506f3, leads to a non-closure of the tagged moisture budget (111% at the end of the example eiffel case). This suggests that also in the rest of the code we fail to account for the decreasing area of the grid cells towards the poles.

The problem is that in calculating the zonal fluxes, we use the same length for the northern and the southern edges.

**Comment by Peter9192** [comment]
The issue was introduced here: https://github.com/WAM2layers/WAM2layers/pull/356/commits/ea053ccc8cbce8033643626086b9588904bf3660.

I figured that `Fy * dx / A` could be approximated as `Fy * dx / (dy * dx) = Fy / dy`, which would retrieve the traditional advection term. First of all, this approximation is not exact, as the area of a grid cell is sort of trapezoidal rather than square. Moreover, by eliminating `dx` we remove the latitude-weighting. Later on, when we stagger the grid, this leads to both the top and the bottom interfaces getting equal weights.

**Comment by BSchilperoort** [comment]
@Peter9192 isn't this fixed now?

**Comment by ruudvdent** [comment]
Yes
