### ISSUE TITLE
Allow for global simulations in tracking

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#46]
In Backward and Forward Tracking add the global simulations option (see settings script and pre-processing for similar code)

**Comment by Peter9192** [comment]
e.g. by adding a setting: periodic=True

**Comment by ruudvdent** [comment]
fixed for preprocessing, but reopened for backward tracking script

**Comment by Imme1992** [comment]
This still need to be checked carefully

**Comment by Imme1992** [comment]
Same as issue #136 
Branch created Global_runs where periodic boundaries are coded in the backtracking script

**Comment by Imme1992** [comment]
Dask needs to be properly installed and used within the program
Dask need to be included in the package installation
Finetuning of loading of global data using dask (make dask optional)

**Comment by Peter9192** [comment]
Possible though might need dask options added in #119 for big arrays.
