### ISSUE TITLE
Add total column water and other integrated fluxes

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#47]
To check the calculation of the fluxes added from the two layers

**Comment by ruudvdent** [comment]
to check, but also to 'correct' the u*q and v*q from the pre-processing

**Comment by ruudvdent** [comment]
code to correct can be found on [https://github.com/ruudvdent/WAM2layersPython](url)

**Comment by Peter9192** [comment]
This has been added, see
https://github.com/WAM2layers/WAM2layers/blob/f7a2c7d93ae9a9a02c3d2b7df3ae083ae5f10327/src/wam2layers/preprocessing/era5.py#L221-L228
