### ISSUE TITLE
let backtracking script check for 2D/3D mask and for values being between 0 and 1

### ISSUE THREAD

**Issue by ruudvdent** [WAM2layers/WAM2layers#55]

**Comment by Imme1992** [comment]
No priority, but negative values or values above 1 lead to wrong results

**Comment by Imme1992** [comment]
We could write a test_regionmask.py to check this, but again, no priority. 
#175 Also provides a script to create a region mask

**Comment by ruudvdent** [comment]
Could be part of PR #251 . issue #252
