### ISSUE TITLE
Add logging among others about stability criterion affects fluxes (given the time frequency)

### ISSUE THREAD

**Issue by ruudvdent** [WAM2layers/WAM2layers#67]

**Comment by Imme1992** [comment]
Print statement or output regarding when the stability correction function is applied.
Stability criterion depends on grid spacing, time stepping, wind speeds, and where you are on the globe (grid spacing different between equator and north pole). 
Logging of criterion in separate file.

**Comment by Imme1992** [comment]
Where and when criterion is not met

**Comment by Imme1992** [comment]
The count of how often the stability criterion is applied (as percentage of the total grid cells) and what is its mean value per timestep is now in the main branch.

**Comment by Imme1992** [comment]
Do we also want to add logging regarding the yaml file settings and copy them to the logging file which should be saved in the directory of where the backtracking is done
