### ISSUE TITLE
Forward tracking

### ISSUE THREAD

**Issue by Peter9192** [WAM2layers/WAM2layers#8]
The current version only does backtracking. Forward tracking is also availabe in https://github.com/ruudvdent/WAM2layersPython ([Con_P_Recyc_Masterscript.py](https://github.com/ruudvdent/WAM2layersPython/blob/master/Con_P_Recyc_Masterscript.py)). It would be great to re-introduce it is this version of the code.

**Comment by ruudvdent** [comment]
Yes, indeed. I would also be in favor of more generically calling it forward tracking and explaining in the readme what kind of analysis and metrics could be calculated (e.g. continental precipitation recycling ratios).

**Comment by ruudvdent** [comment]
will be done when backtracking script is considered 'finished'
