### ISSUE TITLE
Output hourly/daily evaporation and precipitation (within tracked region, or with mask) also from the backtrack script

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#88]

**Comment by Peter9192** [comment]
Perhaps we can add an option in the config file, something like: `output_frequency: 1h` or something like that.

**Comment by Imme1992** [comment]
You can now select the output frequency in your yaml file
Etagged is now also an output of the backtracking
Evaporation is not an ouput of the backtracking but is an input so can be analysed from the input files or the preprocessed files
