### ISSUE TITLE
Bug in backtrack script

### ISSUE THREAD

**Issue by Imme1992** [WAM2layers/WAM2layers#89]
There is still a bug in the backtrack script I think as the output of the east_loss and west_loss variable are the same which should not be the case
And the north_loss and south_loss variable is also the same

**Comment by Imme1992** [comment]
But also not all precip seems to be tracked, I haven't figure out what exactly is the matter.

**Comment by ruudvdent** [comment]
I think this is solved now?

**Comment by Peter9192** [comment]
Yes, in #90
