### ISSUE TITLE
Correct calculation of dp if pressure levels

### ISSUE THREAD

**Issue by chrisweij** [WAM2layers/WAM2layers#91]
The calculation of dp using pressure levels instead of model levels should be checked.

- First, it should be checked/changed that the total dp over all levels is equal to the total column height (from surface pressure to 0 hPa?)
- Secondly, the calculation of dp should be accounted for when separating the data into two layers

**Comment by ruudvdent** [comment]
I think this can in principle be closed per #109, which does this correctly, although the code does not provide feedback on whether it's correct. Do you want to add that @chrisweij ?

**Comment by Imme1992** [comment]
@Peter9192 has local adjustments which still need to be included

**Comment by Imme1992** [comment]
Can you also document this in a log file? What is the correction applied when tcw is used

**Comment by ruudvdent** [comment]
![image](https://github.com/WAM2layers/WAM2layers/assets/10234007/fca98b7b-848c-4ad5-98a5-cb21ae225a15)

**Comment by ruudvdent** [comment]
![image](https://github.com/WAM2layers/WAM2layers/assets/10234007/6bca8030-6fc0-4e08-9aff-cb9ac3156e6a)
