### ISSUE TITLE
Should pandas>=1.4.0 be in requirements?

### ISSUE THREAD

**Issue by chrisweij** [WAM2layers/WAM2layers#96]
In the preprocessing script the parameter `inclusive` is used to create the date_range. This parameter was only introduced in version 1.4.0 from pandas (see https://pandas.pydata.org/docs/reference/api/pandas.date_range.html), so it might be necessary to set this as a requirement (or the code should be changed).

**Comment by Peter9192** [comment]
Good idea 👍

**Comment by Peter9192** [comment]
Done in #122. For users using the 3.0.0.b2 release experiencing issues like "TypeError: _generate_range() got an unexpected keyword argument 'inclusive'", please update pandas manually: `pip install "pandas>=1.4.0"`
